### ISSUE TITLE
Detay

### ISSUE THREAD

**Issue by 0x33c0unt** [sibertime/ctf#1]
.

**Comment by sibertime** [comment]
Merhabalar,

Ctf içeriğini detay incelerseniz bizim sitemiz yerine başka bir yere yönlendirecektir.

İyi Çalışmalar

On 20 Sep 2019, at 23:58, Yusuf Kocadaş <notifications@github.com<mailto:notifications@github.com>> wrote:


Websitesinde bruteforce felan deneyebilirmiyiz ve o kısım sadece web imi kapsıyor diğer açık portlardan da bir şey elde edebilirmiyiz?

**Comment by sibertime** [comment]
Merhabalar,
Web kısmındaki soru sadece web ile ilgilidir. Diğer portları kontrol etmenize gerek yoktur.
İyi ctf ler.

**Comment by 0x33c0unt** [comment]
Çözen oldu mu? Ben stenography de elde ettiğim dosyaya anlam veremedim.

**Comment by 0x33c0unt** [comment]
Sanırım bitti, "1453fatihinistanbulu" şifresiyle resimden çıkardığımız dosyadan sonrasını çok merak ediyorum hatta soruda sıkıntı olmuş bile olabileceği aklıma geldi, çok uğraşmıştım sonuç çıkaramadım. Umarım çözümü paylaşırsınız.

**Comment by sibertime** [comment]
Merhaba,

25.09.2019 tarihinde CTF sorumuzun çözümü Github hesabımız üzerinden yayınlanacaktır. Gelişmeler için Github hesabımızı takip edebilirsiniz.
